# Generated by Django 5.1 on 2024-08-17 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.TextField(max_length=50, verbose_name='first_name')),
                ('last_name', models.TextField(max_length=50, verbose_name='last_name')),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
