# Generated by Django 5.1 on 2024-08-21 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_gender_user_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.TextField(max_length=20, verbose_name='full_name')),
                ('class_grade', models.TextField(max_length=50, verbose_name='class_grade')),
                ('age', models.TextField(max_length=10, verbose_name='age')),
                ('name_school', models.TextField(max_length=30, verbose_name='name_school')),
            ],
        ),
    ]
